import express, { Router } from 'express';
import authRouter from './auth.routes.js';
import courseRouter from './course.routes.js';
import educatorRouter from './educator.routes.js';
import userRouter from './user.routes.js';
import quizRouter from './quiz.routes.js';
import progressRouter from './progress.routes.js';
import learningRouter from './learning.routes.js';
import studentRouter from './student.routes.js';
import bookmarkRouter from './bookmark.routes.js';
import noteRouter from './note.routes.js';
import videoRouter from './video.routes.js';
import instructorRouter from './instructor.routes.js';
import adminRouter from './admin.routes.js';
import paymentRouter from './payment.routes.js';
import subscriptionRouter from './subscription.routes.js';
import certificateRouter from './certificate.routes.js';
import aiRouter from '../modules/ai/ai.routes.js';

const apiRouter: Router = express.Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/courses', courseRouter);
apiRouter.use('/course', courseRouter);
apiRouter.use('/educator', educatorRouter);
apiRouter.use('/instructor', instructorRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/payment', paymentRouter);
apiRouter.use('/subscription', subscriptionRouter);
apiRouter.use('/certificate', certificateRouter);
apiRouter.use('/ai', aiRouter);
apiRouter.use('/user', userRouter);
apiRouter.use('/quiz', quizRouter);
apiRouter.use('/progress', progressRouter);
apiRouter.use('/learning', learningRouter);
apiRouter.use('/student', studentRouter);
apiRouter.use('/bookmarks', bookmarkRouter);
apiRouter.use('/notes', noteRouter);
apiRouter.use('/videos', videoRouter);

export default apiRouter;
